config/routes.rb
CupidWeb::Application.routes.draw do
  root to: "dashboard#show"
  resources :pretenders do
    member do
      put :toggle_reserved
    end
  end
  resources :couples, only: [:create, :destroy] do
    collection do
      post :round
    end
  end

end

app/models/couple.rb
class Couple < ActiveRecord::Base
  attr_accessible :pretender_a, :pretender_b, :pretender_a_id, :pretender_b_id

  belongs_to :pretender_a, class_name: "Pretender"
  belongs_to :pretender_b, class_name: "Pretender"

  scope :without_disabled_pretenders, lambda {
    active_pretenders_ids = Pretender.where(disabled: false).pluck(:id)
    t = arel_table
    where(t[:pretender_a_id].in(active_pretenders_ids).and(t[:pretender_b_id].in(active_pretenders_ids).or(t[:pretender_b_id].eq(nil))))
  }

  scope :for_pretenders, lambda { |pretender_1, pretender_2|
    for_pretender(pretender_1).for_pretender(pretender_2)
  }

  scope :for_pretender, lambda { |pretender|
    t = arel_table
    where(t[:pretender_a_id].eq(pretender.id).or(t[:pretender_b_id].eq(pretender.id)))
  }

  def self.all_iterations_ago
    return Thread.current["all_iterations_ago"] if Thread.current["all_iterations_ago"].present?
    last_couples = Couple.without_disabled_pretenders.
      select('pretender_a_id, pretender_b_id, min(iterations_ago) as iterations_ago').group('pretender_a_id, pretender_b_id')

    Thread.current["all_iterations_ago"] = last_couples.all.inject({}) do |acc, couple|
      acc[couple.pretender_a_id] ||= {}
      acc[couple.pretender_b_id] ||= {} if couple.pretender_b_id

      if acc[couple.pretender_a_id][couple.pretender_b_id].nil? || couple.iterations_ago < acc[couple.pretender_a_id][couple.pretender_b_id].to_i
        acc[couple.pretender_a_id][couple.pretender_b_id] = couple.iterations_ago
        acc[couple.pretender_b_id][couple.pretender_a_id] = couple.iterations_ago if couple.pretender_b_id
      end

      acc
    end
  end
end

app/models/pretender.rb
class Pretender < ActiveRecord::Base
  attr_accessible :name, :disabled, :reserved

  scope :enabled, where(disabled: false)
  default_scope order("name ASC")

  def iterations_ago_with(pretender)
    all_iterations = Couple.all_iterations_ago[self.id]
    return nil if all_iterations.blank?
    all_iterations[pretender.id]
  end

  def has_couple?
    all_iterations = Couple.all_iterations_ago[self.id]
    return false if all_iterations.blank?
    all_iterations.values.min == 0
  end

  def self.any_single?
    return true if Pretender.enabled.count != Couple.all_iterations_ago.keys.size
    Couple.all_iterations_ago.values.any? { |it_ago| !it_ago.values.include?(0) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  after_filter do
    Thread.current["all_iterations_ago"] = nil
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController

  # POST /couples
  def create
    couple = Couple.new(params[:couple])

    respond_to do |format|
      if couple.save
        format.html { redirect_to root_path, notice: 'Couple was successfully created.' }
      else
        format.html { redirect_to root_path, alert: 'Error creating the couple.' }
      end
    end
  end

  # DELETE /couples/destroy
  def destroy
    Couple.where(id: params[:id], iterations_ago: 0).destroy_all
    redirect_to root_path
  end

  # POST /couples/round
  def round
    unless Pretender.any_single?
      Couple.update_all("iterations_ago = iterations_ago + 1")
      Pretender.update_all(reserved: false)
    end
    redirect_to root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @pretenders = Pretender.enabled
    @couples = Couple.where(iterations_ago: 0).includes(:pretender_a, :pretender_b)
  end
end

app/controllers/pretenders_controller.rb
class PretendersController < ApplicationController
  # GET /pretenders
  # GET /pretenders.json
  def index
    @pretenders = Pretender.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pretenders }
    end
  end

  # GET /pretenders/1
  # GET /pretenders/1.json
  def show
    @pretender = Pretender.find(params[:id])
    @couples = Couple.for_pretender(@pretender).order(:iterations_ago)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pretender }
    end
  end

  # GET /pretenders/new
  # GET /pretenders/new.json
  def new
    @pretender = Pretender.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pretender }
    end
  end

  # GET /pretenders/1/edit
  def edit
    @pretender = Pretender.find(params[:id])
  end

  # POST /pretenders
  # POST /pretenders.json
  def create
    @pretender = Pretender.new(params[:pretender])

    respond_to do |format|
      if @pretender.save
        format.html { redirect_to pretenders_url, notice: 'Pretender was successfully created.' }
        format.json { render json: @pretender, status: :created, location: @pretender }
      else
        format.html { render action: "new" }
        format.json { render json: @pretender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pretenders/1
  # PUT /pretenders/1.json
  def update
    @pretender = Pretender.find(params[:id])

    respond_to do |format|
      if @pretender.update_attributes(params[:pretender])
        format.html { redirect_to pretenders_url, notice: 'Pretender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pretender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pretenders/1
  # DELETE /pretenders/1.json
  def destroy
    @pretender = Pretender.find(params[:id])
    @pretender.destroy

    respond_to do |format|
      format.html { redirect_to pretenders_url }
      format.json { head :no_content }
    end
  end

  def toggle_reserved
    @pretender = Pretender.find(params[:id])

    @pretender.update_attribute :reserved, !@pretender.reserved?

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pretenders_helper.rb
module PretendersHelper
  def partner_name(couple, pretender)
    return "- Solo -" if couple.pretender_b.nil?
    couple.pretender_a == pretender ? couple.pretender_b.name : couple.pretender_a.name
  end
end

app/views/dashboard/show.html.erb
<h2>Pretenders</h2>
<table class='table dashboard'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <% @pretenders.each do |pretender| %>
        <th><%= link_to pretender.name, pretender %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @pretenders.each_with_index do |row_owner| %>
      <tr>
        <th>
          <%= link_to toggle_reserved_pretender_path(row_owner), :method => :put, :class => (row_owner.reserved? ? "reserved" : "free") do %>
            <% if row_owner.reserved? %>
              unreserve
            <% else %>
              reserve
            <% end %>
          <% end %>
        </th>
        <th><%= link_to row_owner.name, row_owner %></th>
        <% @pretenders.each do |pretender| %>
          <% if pretender.has_couple? || row_owner.has_couple? %>
            <td class='disabled'></td>
          <% elsif pretender.reserved? && row_owner.reserved? && pretender != row_owner %>
            <td class='disabled'></td>
          <% elsif pretender == row_owner %>
            <td class='create-couple'>
              <%= link_to 'solo', couples_path(couple: {pretender_a_id: pretender.id}), method: :post, class: 'solo' %>
            </td>
          <% else %>
            <% ago = pretender.iterations_ago_with(row_owner) %>
            <td class='create-couple'>
              <%= link_to couples_path(couple: {pretender_a_id: row_owner.id, pretender_b_id: pretender.id}), method: :post do %>
                <span class="ago"><%= ago %></span>
              <% end %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Current couples <%= link_to "Next iteration!", round_couples_path, method: 'post' unless Pretender.any_single? %></h2>

<ul>
  <% @couples.each do |couple| %>
    <li>
      <%= couple.pretender_a.name %>
      <% if couple.pretender_b %>
        &amp; <%= couple.pretender_b.name %>
      <% else %>
        (Solo)
      <% end %>

      <%= link_to "(remove)", couple_path(couple), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cupid!</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Cupid!", root_path, class: 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Pretenders", pretenders_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span12"><%= yield %></div>
    </div>
  </div>
</body>
</html>

app/views/pretenders/_form.html.erb
<%= form_for @pretender, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Pretender</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :disabled, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :disabled %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', pretenders_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/pretenders/edit.html.erb
<%= render :partial => 'form' %>

app/views/pretenders/index.html.erb
<h1>Pretenders</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @pretenders.each do |pretender| %>
      <tr>
        <td><%= pretender.id %></td>
        <td>
          <% if pretender.disabled? %>
            <i class="icon-off"></i>
          <% end %>
          <%= link_to pretender.name, pretender_path(pretender) %>
        </td>
        <td><%= pretender.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_pretender_path(pretender), :class => 'btn btn-mini' %>

          <% if pretender.disabled? %>
            <%= link_to 'Enable', pretender_path(pretender, pretender: {disabled: false}), :class => 'btn btn-mini btn-info', method: :put %>
          <% else %>
            <%= link_to 'Disable', pretender_path(pretender, pretender: {disabled: true}), :class => 'btn btn-mini btn-warning', method: :put %>
          <% end %>
          <%= link_to 'Destroy', pretender_path(pretender), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_pretender_path, :class => 'btn btn-primary' %>

app/views/pretenders/new.html.erb
<%= render :partial => 'form' %>

app/views/pretenders/show.html.erb
<h1>Pretender</h1>

<p>
  <b>Name</b><br>
  <%= @pretender.name %>
</p>

<p>
  <b>Disabled</b><br>
  <%= @pretender.disabled? ? "Yes" : "No" %>
</p>

<h2>Previous couples</h2>
<ul>
  <% @couples.each do |couple| %>
    <li>
      <b><%= partner_name(couple, @pretender) %></b> (<%= couple.iterations_ago %> iterations ago)
    </li>
  <% end %>
</ul>

<div class="form-actions">
  <%= link_to 'Back', pretenders_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_pretender_path(@pretender), :class => 'btn' %>
  <%= link_to 'Delete', pretender_path(@pretender), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>